stages:
  - build
  - deploy

build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
  script:
    - docker build . -t cr.yandex/crplbtriubvbt4s95dg7/diplom-app:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push cr.yandex/crplbtriubvbt4s95dg7/diplom-app:gitlab-$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: gcr.io/cloud-builders/kubectl:latest
  script:
    - kubectl config set-cluster k8s-regional --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s-regional --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" k8s.yaml
    - kubectl --token="$KUBE_TOKEN" apply -f k8s.yaml
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(\d+\.\d+)$/
